spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam?useSSL=false
    username: root
    password: testtest
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.mysql.sql

blog:
  title: "Blog example"
  subtitle: "Java test"
  phone: "+7 911 193 71 00"
  email: "fxmike@mail.ru"
  copyright: "Fedorov Mikhail"
  copyrightFrom: "2022"
